name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Verify Versions
        run: |
          php -v
          composer --version

      - name: Install Composer dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --no-interaction

      - name: Run tests
        run: |
          php tests/run_all.php
